import { 
  BrainCircuit, 
  BarChart3, 
  Image, 
  Activity, 
  Settings, 
  Globe,
  ShieldCheck,
  Zap,
  Box,
  Terminal,
  Cpu,
  Database,
  Cloud,
  Lock,
  Wifi,
  Radio,
  LucideIcon
} from 'lucide-react';
import { AppTileConfig } from './types';

export const ICON_MAP: Record<string, LucideIcon> = {
  BrainCircuit,
  BarChart3,
  Image,
  Activity,
  Settings,
  Globe,
  ShieldCheck,
  Zap,
  Box,
  Terminal,
  Cpu,
  Database,
  Cloud,
  Lock,
  Wifi,
  Radio
};

export const DEFAULT_APP_TILES: AppTileConfig[] = [
  {
    id: 'ai-core',
    title: 'Nexus AI',
    description: 'Advanced neural processing unit interface.',
    icon: 'BrainCircuit',
    color: 'cyan',
    route: '/app/ai-core',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'cyan',
    gradientIntensity: 50
  },
  {
    id: 'analytics',
    title: 'Data Vis',
    description: 'Real-time market analytics and projections.',
    icon: 'BarChart3',
    color: 'purple',
    route: '/app/analytics',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'purple',
    gradientIntensity: 50
  },
  {
    id: 'media',
    title: 'Media Hub',
    description: 'Holographic asset management system.',
    icon: 'Image',
    color: 'pink',
    route: '/app/media',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'pink',
    gradientIntensity: 50
  },
  {
    id: 'system',
    title: 'Sys Status',
    description: 'Network topology and server health.',
    icon: 'Activity',
    color: 'emerald',
    route: '/app/system',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'emerald',
    gradientIntensity: 50
  },
  {
    id: 'security',
    title: 'Guardian',
    description: 'Firewall and intrusion detection.',
    icon: 'ShieldCheck',
    color: 'blue',
    route: '/app/security',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'blue',
    gradientIntensity: 50
  },
  {
    id: 'power',
    title: 'Energy Grid',
    description: 'Power distribution monitoring.',
    icon: 'Zap',
    color: 'amber',
    route: '/app/power',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'amber',
    gradientIntensity: 50
  },
  {
    id: 'network',
    title: 'Global Net',
    description: 'Satellite uplink controls.',
    icon: 'Globe',
    color: 'indigo',
    route: '/app/network',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'indigo',
    gradientIntensity: 50
  },
  {
    id: 'settings',
    title: 'Config',
    description: 'User preferences and interface settings.',
    icon: 'Settings',
    color: 'slate',
    route: '/app/settings',
    appType: 'html',
    appContent: '',
    deployUrl: '',
    imageUrl: '',
    imageBrightness: 70,
    titleColor: 'white',
    descriptionColor: 'white',
    gradientColor: 'slate',
    gradientIntensity: 50
  }
];
